import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { appConfig } from "@/config/app";
import { Toaster } from "@ui/components/ui/sonner";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

const roboto = Roboto({
	variable: "--font-roboto",
	weight: ["400", "500", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: appConfig.name,
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await getLocale();

	return (
		<html lang={locale}>
			<body className={`${roboto.variable} antialiased`}>
				<NextIntlClientProvider>
					{children}
					<Toaster richColors />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
